### ISSUE TITLE
Intelligently request the same transaction from multiple nodes

### ISSUE THREAD

**Issue by mrBliss** [IntersectMBO/ouroboros-network#1743] opened 2020-03-04 10:15 UTC
Splitting off option (3) from #1161:

> Keep track of which `TxIds` we're asking from which peers and don't ask for the same one from multiple peers unless that would otherwise cause things to stall, in which case we should make another request for the same `TxId`.

Say a node just connected to the network and has an empty Mempool, it might end up requesting the exact same transaction (the first tx in all the other nodes' Mempools) from all nodes concurrently.

Just like for BlockFetch, we could have a "bulk sync" mode (don't request the same tx from multiple nodes, maximise bandwidth) and a "deadline" mode (request the same tx from a *configurable* number of nodes, minimise latency), based on, e.g., Mempool size.

Potential approach: keep a `Map txid ConcurrentRequests` in (a var in) the `NodeKernel` (like `RecentTxIds` in #1476) where the `ConcurrentRequests` is a `Word`. Not just a `Set txid`, because we want to allow concurrent requests in the deadline mode. We have to be careful with requests that don't get replies, they should be retried after a timeout.

**Comment by coot** [comment] 2023-12-20 10:57
Duplicate of #3311.

**Closed by coot** 2023-12-20 10:57 UTC
Labels: optimisation, tx-submission
