### ISSUE TITLE
coot/dns branch broke dns test

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#1930] opened 2020-04-09 18:37 UTC
```
Subscription
    Resolve (Sim):                                             FAIL
      *** Failed! Falsified (after 1 test):
      LookupResult: ipv4: Left RetryLimitExceeded delay 2.272s ipv6: Right [] delay 2.288s rtt 0.095s
      Use --quickcheck-replay=772791 to reproduce.
    Resolve Subscribe (IO): 
```

**Comment by bolt12** [comment] 2024-07-18 11:25
Can't reproduce, so I will close this. Perhaps it got fixed:

![image](https://github.com/user-attachments/assets/96da22d7-a312-49cb-9a0d-0745dcb33890)
![image](https://github.com/user-attachments/assets/00ab3933-4076-4d03-81c2-06d3671a02cb)

**Closed by bolt12** 2024-07-18 11:25 UTC
Labels: bug
